skit:
  # configure default field type for primary keys.
  # it is recommended to configure it before creating your entities
  # possible values are "bigint" and "ulid" (see https://symfony.com/doc/current/components/uid.html)
  default_primary_key_field_type: 'ulid'


skit_rest_helper:
  scan:
    - '%kernel.project_dir%/vendor/skit/core-bundle/src/Controller'


framework:
  cache:
    pools:
      resource_schema_cache:
        adapter: cache.adapter.system
  messenger:
    transports:
      async_tasks:
        dsn: '%env(MESSENGER_TASKS_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 0
    routing:
      'Skit\Bundle\CoreBundle\Message\ProcessTaskMessage': async_tasks


doctrine:
  dbal:
    types:
      datetime_immutable_utc: Skit\Bundle\CoreBundle\Component\Resource\Doctrine\DBAL\Types\UTCDateTimeImmutable
    connections:
      default:
        mapping_types:
          enum: string
      tasks:
        url: '%env(resolve:TASKS_DATABASE_URL)%'
        mapping_types:
          enum: string
  orm:
    entity_managers:
      default:
        mappings:
          gedmo_translatable:
            type: annotation
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
            alias: GedmoTranslatable
            is_bundle: false
      tasks:
        connection: tasks
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware


doctrine_migrations_multiple_database:
  entity_managers:
    default:
      migrations_paths:
        DoctrineMigrations\Main: '%kernel.project_dir%/migrations/Main'
    tasks:
      migrations_paths:
        DoctrineMigrations\Tasks: '%kernel.project_dir%/migrations/Tasks'


stof_doctrine_extensions:
  default_locale: en
  translation_fallback: true
  orm:
    default:
      translatable: true
